### ISSUE TITLE
Custom IdentityUser

### ISSUE THREAD

**Issue by paulomonteirodev** [NetDevPack/NetDevPack.Identity#3]
I liked the package, but I would like to use the IdentityUser with the ID with Int type, however the method that generates the JWT does not currently allow a generic implementation.
----------------------------------------------------------------
Gostei do pack mas queria usar o IdentityUser com o Id do tipo Int, porém o metodo que gera o JWT não permite uma implementação genérica atualmente.

**Comment by EduardoPires** [comment]
English please :)
The package provides support. You will need to provide your own DbContext and Identity user with this customization.

This approach is implemented in our sample:

https://github.com/NetDevPack/NetDevPack.Identity/blob/master/src/Samples/AspNetCore.Jwt.Sample/Config/CustomIdentityConfig.cs

And here

https://github.com/NetDevPack/NetDevPack.Identity/blob/master/src/Samples/AspNetCore.Jwt.Sample/Controllers/AuthCustomConfigController.cs

**Comment by paulomonteirodev** [comment]
Ok, I'm going to see the example and implement it here. Thank you.

**Comment by paulomonteirodev** [comment]
It doesn't work because JwtBuilder needs a type of IdentityUser and IdentityUser inherits of IdentityUser<string>

**Comment by EduardoPires** [comment]
Fixed at #4
