### ISSUE TITLE
Use a LDAP Server or ActiveDirectory to authenticate

### ISSUE THREAD

**Issue by nunonux** [NetDevPack/NetDevPack.Identity#5]
**Is your feature request related to a problem? Please describe.**
Could be possible if the library use a LDAP or ActiveDirectory to authenticate and then return the JWT Token?

**Describe the solution you'd like**
So we could build like an interface where we would create the implementation and with it create the JWT Token with claims and any other thing required.

**Comment by EduardoPires** [comment]
Yes is possible, however I think that implementation needs an exclusive package to doesn't force the project carry the LDAP dependencies without use.
