### ISSUE TITLE
Refresh JWT Token generated?

### ISSUE THREAD

**Issue by moreira-daniel** [NetDevPack/NetDevPack.Identity#6]
Any recommended implementation on updating (refrash) the JWT token generated by this package?

**Comment by EduardoPires** [comment]
Refresh token isn't a native feature from Identity, is possible, but I think is better to do in your application not in component, but I'll think about :)

**Comment by brunohbrito** [comment]
Hi @moreira-daniel 

The package supposed to do it is other one, [Security.JwtSigningCredentials](https://github.com/NetDevPack/Security.JwtSigningCredentials).

Anyway, these packages handle the hability to generate a Key to Sign your JWT and validate it between API's without sharing the private key, only a public key. 

The routines about JWT Token generation and Refresh tokens you have to do it.

**Comment by brunobritodev** [comment]
Refresh token is now available.
